# fiwix/drivers/pci/Makefile
#
# Copyright 2022, Jordi Sanfeliu. All rights reserved.
# Distributed under the terms of the Fiwix License.
#

.c.o:
	$(CC) $(CFLAGS) -c -o $@ $<

OBJS = pci.o

all:	$(OBJS)

clean:
	rm -f *.o

